baseURL = 'https://harsha-y.github.io'
languageCode = 'en-us'
title = 'Harsha Yalamanchili'
theme = "PaperMod"
enableGitInfo = true
enableRobotsTXT = false
[taxonomies]
  category = 'categories'
  tag = 'tags'

params:
  env: production
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
